# Generated by Django 5.2.5 on 2025-09-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready')], default='processing', max_length=20),
        ),
    ]
